version: '3.1'
services:
  mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=commands
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
 
 
    volumes:
      - target-data:/var/lib/mysql


  app:
    container_name: dotnetcore-mysqldb
    image: rolandsall24/dotnetapi-command-saver:1.0.3-env-local
    build: ./
    ports:
      - "5000:80"
    depends_on:
      - mysqldb

volumes:
  target-data:
